import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const DMSerifDisplay = localFont({
 src: "./fonts/DMSerifDisplay/DMSerifDisplay-Regular.ttf",
 variable: "--font-dm-serif-display",
 weight: "100 900"
});


const inter = localFont({
   src: "./fonts/inter/Inter-VariableFont.ttf",
  variable: "--font-inter",
   weight: "100 900"
});

const clashGrotesk= localFont({
  src: "./fonts/ClashGrotesk/ClashGrotesk-Variable.ttf",
  variable: "--font-clash-grotesk",
  weight: "100 900"
});

const plusJakarta= localFont({
  src: "./fonts/PlusJakarta/PlusJakartaSans.ttf",
  variable: "--font-plus-jakarta",
  weight: "100 900"
});
const spaceGrotesk= localFont({
  src: "./fonts/SpaceGrotesk/SpaceGrotesk.ttf",
  variable: "--font-space-grotesk",
  weight: "100 900"
});
const outfit= localFont({
  src: "./fonts/outfit/Outfit-VariableFont.ttf",
  variable: "--font-outfit",
  weight: "100 900"
});
export const metadata: Metadata = {
  title: "Debatrix",
  description: "Generated by niixass",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${DMSerifDisplay.variable} ${clashGrotesk.variable} ${plusJakarta.variable} ${spaceGrotesk.variable} ${outfit.variable} antialiased  bg-bgDark w-screen h-screen `}
      >
        {children}
      </body>
    </html>
  );
}
